# -*- coding: utf-8 -*-
"""Guilherme de Paula Cardoso - Correlacao-Exercicios.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IcwJshqAOHpyU4vysrGki4zvF6F28bNX
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""# Correlação - Exercícios

## Exercício 01
É esperado que a massa muscular de uma pessoa diminua com a idade. Para estudar essa relação, uma nutricionista selecionou $18$ mulheres, com idade entre $40$ e $79$ anos, e observou em cada uma delas a idade e a massa muscular.


|Massa muscular|Idade|
|-|-|
|82.0|	71.0|
|91.0|	64.0|
|100.0|	43.0|
|68.0|	67.0|
|87.0|	56.0|
|73.0|	73.0|
|78.0|	68.0|
|80.0|	56.0|
|65.0|	76.0|
|84.0|	65.0|
|116.0|	45.0|
|76.0|	58.0|
|97.0|	45.0|
|100.0|	53.0|
|105.0|	49.0|
|77.0|	78.0|
|73.0|	73.0|
|78.0|	68.0|

Calcule o coeficiente de correlação entre a idade e a massa muscular. Apresente o gráfico de dispersão.

Fonte: Adaptado de (LACHOS, 2007).
"""

mulheres = pd.DataFrame(
    {'Massa Muscular': 
     {0: 82, 1: 91, 2: 100, 3: 68, 4: 87, 5: 73, 6: 78, 7: 80, 8: 65, 9: 84, 10: 116, 11: 76, 12: 97, 13: 100, 14: 105, 15: 77, 16: 73, 17: 78}, 
     'Idade': 
     {0: 71, 1: 64, 2: 43, 3: 67, 4: 56, 5: 73, 6: 68, 7: 56, 8: 76, 9: 65, 10: 45, 11: 58, 12: 45, 13: 53, 14: 49, 15: 78, 16: 73, 17: 68}}
)
mulheres.plot.scatter('Massa Muscular','Idade')

"""## Exercício 02
Um pesquisador deseja verificar se um instrumento para medir a concentração de determinada substância no sangue está bem calibrado. Para isto, ele tomou $15$ amostras de concentrações conhecidas (`X`) e determinou a respectiva concentração através do instrumento (`Y`), obtendo:

| | | | | | | | | | | | | | | | |
|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|
|`X`|2|2|2|4|4|4|6|6|6|8|8|8|10|10|10|
|`Y`|2.1|1.8|1.9|4.5|4.2|4|6.2|6|6.5|8.2|7.8|7.7|9.6|10|10.1|

Sobre as variáveis `X` e `Y`, responda:
- As variáveis estão fortemente ou fracamente correlacionadas? 
- A correlação é positiva ou negativa?
- Apresente o gráfico de dispersão das variáveis.


Fonte: Adaptado de (LACHOS, 2007).
"""

amostras = pd.DataFrame(
    {'x': 
     {0: 2, 1: 2, 2: 2, 3: 4, 4: 4, 5: 4, 6: 6, 7: 6, 8: 6, 9: 8, 10: 8, 11: 8, 12: 10, 13: 10, 14: 10}, 
     'y': 
     { 0: 2.1, 1: 1.8, 2: 1.9, 3: 4.5, 4: 4.2, 5: 4, 6: 6.2, 7: 6, 8: 6.5, 9: 8.2, 10: 7.8, 11: 7.7, 12: 9.6, 13: 10, 14: 10.1 }}
)
amostras['x'].corr(amostras['y'])

"""Fortemente correlacionadas
Positiva
"""

amostras.plot.scatter('x','y')

"""## Exercício 03
Carregue a base de dados `alugueis`, e reponda as questões a seguir.
```python
#No Colab:
from google.colab import drive
drive.mount('/drive')
alugueis = pd.read_csv('/drive/Shared drives/BasesPublicas/Bases/Exemplos/alugueis.csv', sep=',', encoding='latin1')
#No Jupyter:
# alugueis = pd.read_csv('alugueis.csv', sep=',', encoding='latin1')
```
Fonte da base: Adaptada de (JUNIOR, 2020).
"""

# No Colab:
from google.colab import drive
drive.mount('/drive')
alugueis = pd.read_csv('/drive/Shared drives/BasesPublicas/Bases/Exemplos/alugueis.csv', sep=',', encoding='latin1')
# No Jupyter:
# alugueis = pd.read_csv('alugueis.csv', sep=',', encoding='latin1')

"""1. O que influencia mais o valor do aluguel? A área do imóvel ou o número de banheiros?
1. O que influencia mais no valor da taxa de condominio: o número de vagas de garagem ou o número de quartos? Essa correlação é significativa?
1. Qual variável está mais correlacionada com a área do imóvel: o número de vagas na garagem ou o número de banheiros?
1. Na base, podemos considerar que as casas possuem andar como '-'. Considere que os que os registros que possuem andar como apartamentos. Desta forma, responda:
    1. O aluguel é maior ou menor nos andares mais altos?
        1. Podemos dizer que isso acontece? A correlação é significativa?
        1. Faça o gráfico de dispersão, considerando número do andar e valor do aluguel.
"""

print("Area:", alugueis['Aluguel'].corr(alugueis['Area']))
print("Banheiros:", alugueis['Aluguel'].corr(alugueis['Banheiros']))
print("Banheiros influencia mais no valor do aluguel")

print("Quartos:", alugueis['Condominio'].corr(alugueis['Quartos']))
print("Garagens:", alugueis['Condominio'].corr(alugueis['Vagas']))
print("O número de garagens influencia mais, mesmo não sendo significativo")

print("Banheiros:", alugueis['Area'].corr(alugueis['Banheiros']))
print("Garagens:", alugueis['Area'].corr(alugueis['Vagas']))
print("O número de banheiros influencia mais")

aptos = alugueis.iloc[alugueis.index[alugueis["Andar"] != "-"]]

print("Correlação:", aptos['Aluguel'].corr(aptos['Andar'].astype('int64')))
print("O Aluguel é mais alto em andares mais altos")

print("Sim, porque o índice de correlação é maior do que 0.05")

aptos['andar_'] = aptos['Andar'].astype('int64')

aptos.plot.scatter('Aluguel','andar_')

"""# Referências

[LACHOS, H. Estatística para experimentalistas: Notas de aula. Unicamp, 2007.](http://www.ime.unicamp.br/~hlachos/ME414_2007.html)  
[JUNIOR, R. *brazilian_houses_to_rent*. Kaggle, 2020](https://www.kaggle.com/rubenssjr/brasilian-houses-to-rent/metadata)  


"""