# -*- coding: utf-8 -*-
"""Guilherme de Paula Cardoso - Exercicios_Elementos_de_estatistica_I.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wx6orlN0PF5oCZnpfXUqWcNBBGg7F30h

# Elementos de Estatística I - Exercícios

---
"""

########################
#Bibliotecas necessárias
########################

#Pandas
import pandas as pd
import math

# Solicita acesso ao Google Drive
from google.colab import drive
drive.mount('/drive')

"""# ENEM 1998
Carregue a base de dados do ENEM do ano de 1998, e responda a cada questão elencada abaixo.

A descrição detalhada da base de dados está disponível neste [link](https://docs.google.com/spreadsheets/d/1tKI5o9wBzBh_SaRccHJKwEzqIekqhyze/edit#gid=1105751035).


Fonte dos dados: [Microdados do Exame Nacional do Ensino Médio - Enem](http://www.dados.gov.br/dataset/microdados-do-exame-nacional-do-ensino-medio-enem) 

Para importar a base:
```python
# Carrega a base de dados direto do Google Drive (Executando no Google Colab)
enem98 = pd.read_csv('/drive/Shared drives/BasesPublicas/Bases/ENEM/1998/MICRODADOS_ENEM_1998.csv', sep=';', encoding='latin1' )
#Mostra as primeiras linhas do DataFrame
enem98.head()
```
"""

# Carrega a base de dados direto do Google Drive (Executando no Google Colab)
enem98 = pd.read_csv('/drive/Shared drives/BasesPublicas/Bases/ENEM/1998/MICRODADOS_ENEM_1998.csv', sep=';', encoding='latin1' )
#Mostra as primeiras linhas do DataFrame
enem98.head()

"""Sobre a base de dados **enem98**, responda as alternativas abaixo:

- Qual é a idade média dos alunos?
"""

enem98['NU_IDADE'].mean()

"""- Qual sexo teve maior número de inscritos?"""

enem98['TP_SEXO'].value_counts()

"""- Qual é a idade dos alunos que mais aparece?"""

enem98['NU_IDADE'].value_counts()

"""- Qual é o desvio padrão da idade, com 0 graus de liberdade?"""

dp = enem98['NU_IDADE'].std(ddof=0) #desvio padrão
print(f'Desvio padrão: {dp:0f}')#2 casas decimais

"""- Qual é o município que possui mais alunos?"""

enem98['NO_MUNICIPIO_RESIDENCIA'].value_counts()

"""- Qual o estado em que o maior número de estudantes reside?"""

enem98['SG_UF_RESIDENCIA'].value_counts()

"""- Qual competência possui a nota com menor variância entre os alunos, da prova objetiva?"""

desv_comp1 = enem98['VL_PERC_COMP1'].std(ddof=0)
desv_comp2 = enem98['VL_PERC_COMP2'].std(ddof=0)
desv_comp3 = enem98['VL_PERC_COMP3'].std(ddof=0)
desv_comp4 = enem98['VL_PERC_COMP4'].std(ddof=0)
desv_comp5 = enem98['VL_PERC_COMP5'].std(ddof=0)

variacoes = pd.Series([desv_comp1,desv_comp2,desv_comp3,desv_comp4,desv_comp5])
variacoes.min()

"""- Qual competência possui a nota com maior variância entre os alunos, da prova objetiva?"""

desv_comp1 = enem98['VL_PERC_COMP1'].std(ddof=0)
desv_comp2 = enem98['VL_PERC_COMP2'].std(ddof=0)
desv_comp3 = enem98['VL_PERC_COMP3'].std(ddof=0)
desv_comp4 = enem98['VL_PERC_COMP4'].std(ddof=0)
desv_comp5 = enem98['VL_PERC_COMP5'].std(ddof=0)
 
variacoes = pd.Series([desv_comp1,desv_comp2,desv_comp3,desv_comp4,desv_comp5])
variacoes.max()

"""- Qual a profissão ou ocupação do pai da maioria dos alunos?"""

enem98['Q11'].value_counts()

"""- Qual a profissão ou ocupação da mãe da maioria dos alunos?"""

enem98['Q13'].value_counts()

"""- Qual o grau de escolaridade do pai da maioria dos alunos?"""

enem98['Q10'].value_counts()

"""- Qual o grau de escolaridade da mãe da maioria dos alunos?"""

enem98['Q12'].value_counts()

"""## Relações Brasil e França

Exercício adaptado de **(ENEM 2009)**


Brasil e França têm relações comerciais há mais de 200 anos. Enquanto a França é a 5ª nação mais rica do planeta, o Brasil é a 10ª, e ambas se destacam na economia mundial. No entanto, devido a uma série de restrições, o comércio entre esses dois países ainda não é adequadamente explorado, como mostra a tabela seguinte, referente ao período 2003-2007. Os valores apresentados correspondem aos investimentos bilaterais, em milhões de dólares.

|Ano|Brasil na França| França no Brasil|
|----|---|---|
|2003|367|825|
|2004|357|485|
|2005|354|1458|
|2006|539|744|
|2007|280|1214|

Utilizando a biblioca Pandas, responda:

Os dados da tabela mostram que, no período considerado, os valores médios dos investimentos da França no Brasil foram maiores que os investimentos do Brasil na França. Quanto a mais foi investido, em média?
"""

br = pd.Series([367,357,354,539,280]).mean()
print(br)

fr = pd.Series([825,485,1458,744,1214]).mean()
print(fr)

"""## Partidas de basquete

Exercício adaptado de (ENEM/2011)

O quadro indica a quantidade de pontos marcados, em quatro partidas, por cinco jogadores de uma mesma equipe de basquete. 

|Jogador|1.ª partida| 2.ª partida| 3.ª partida| 4.ª partida|
|-|--|--|--|--|
|A|31|22|18|9|
|B|15|25|25|15|
|C|20|23|19|18|
|D|18|22|24|16|
|E|17|19|20|24|



Como todos os jogadores obtiveram a mesma média de pontos por partida, para definir quem, entre os cinco atletas, foi o de melhor rendimento, o técnico da equipe resolveu escolher aquele de maior regularidade. Dessa forma, ele escolheu qual jogador? Responda utilizando a biblioteca Pandas.

Para criar um DataFrame com os dados pode ser utilizado um dicionário, como no exemplo abaixo:
#### Exemplo
```python
jogadores = pd.DataFrame(
    {
    'A':[31,22,18,9],
    'B':[15,25,25,15],
    'C':[20,23,19,18],
    'D':[18,22,24,16],
    'E':[17,19,20,24]
    },
    index=['P1','P2','P3','P4'])
jogadores
```
"""

jogadores = pd.DataFrame(
    {
    'A':[31,22,18,9],
    'B':[15,25,25,15],
    'C':[20,23,19,18],
    'D':[18,22,24,16],
    'E':[17,19,20,24]
    },
    index=['P1','P2','P3','P4'])
jogadores

a = jogadores['A']
b = jogadores['B']
c = jogadores['C']
d = jogadores['D']
e = jogadores['E']

dpa = a.std(ddof=0)
print(f'Desvio A: {dpa:0.2f}')
dpb = b.std(ddof=0)
print(f'Desvio B: {dpb:0.2f}')
dpc = c.std(ddof=0)
print(f'Desvio C: {dpc:0.2f}')
dpd = d.std(ddof=0)
print(f'Desvio D: {dpd:0.2f}')
dpe = e.std(ddof=0)
print(f'Desvio E: {dpe:0.2f}')

# JOGADOR C - Tem o menor desvio