# -*- coding: utf-8 -*-
"""Guilherme de Paula Cardoso - Exercicios_regressao_linear.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GC6-zD4h2hebdpfQggEp3a8Z3dSe_hUF

# Exercícios

Utilizando regressão linear para estimar valores, responda as questões apresentadas abaixo. Utilize a base de dados `rioAptos`, disponibilizada em [BasesPublicas](https://drive.google.com/drive/folders/166mbePwjfMhmCOR0ogv2n9rNLtv3uiJB).

1. Qual é o valor estimado do condomínio de um apartamento que custa 90 mil reais no bairro da Tijuca?
    1. Apresente o gráfico de dispersão dos dados, em conjunto com:
        1. a reta que representa a regressão linear entre as duas variáveis consideradas
        - um ponto destacando o valor estimado para o valor de apartamento de 90 mil reais
    - Qual é o erro médio absoluto da regressão?
- Se o valor do condomínio de determinado apartamento situado no bairro do Leblon é mil reais, qual seria o valor aproximado do apartamento?
    1. Apresente o gráfico de dispersão dos dados, em conjunto com:
        1. a reta que representa a regressão linear entre as duas variáveis consideradas
        - um ponto destacando o valor estimado para o valor de apartamento com condomínio de mil reais
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np #Numpy
import pandas as pd #Pandas
import matplotlib.pyplot as plt #Matplotlib
from sklearn.linear_model import LinearRegression #Regressão linear
from sklearn import metrics #Cálculo do erro
# %matplotlib inline

# Verifica se está no colab
COLAB = 'google.colab' in str(get_ipython())
if COLAB:
    print('Executando no Google Colaboratory. Preparando variáveis...')
    from google.colab import drive
    drive.mount('/drive')
    #Altera o diretório onde estão os arquivos 
    DATAPATH='/drive/Shared drives/BasesPublicas/Bases/Exemplos/'

rioAptos = pd.read_csv(DATAPATH+'rioAptos.csv')
rioAptos

rl = LinearRegression()
tijuca = rioAptos['bairro'] == "Tijuca"
temp_tijuca =  rioAptos[tijuca]
preco_tijuca  =  rioAptos['preco'] >= 90000
temp_preco_tijuca = temp_tijuca[preco_tijuca]

precos = temp_preco_tijuca['preco'].values.reshape(-1,1)
condominios = temp_preco_tijuca['condominio'].values.flatten()

rl.fit(precos, condominios)

preco = [90000]
print('Preços:', preco)
conds = rl.predict(np.array(preco).reshape(-1,1))
print('Condominios:', conds)

plt.scatter(precos, condominios)
plt.scatter(preco, conds, color='red')
plt.plot([0,preco[0]],[0, int(conds)],color='red')

EMA = metrics.mean_absolute_error(condominios, rl.predict(np.array(precos).reshape(-1,1)))
print('Média asbsoluta dos erros:', EMA )

rl = LinearRegression()
leblon = rioAptos['bairro'] == "Leblon"
temp_leblon =  rioAptos[leblon]
preco_leblon  =  rioAptos['condominio'] >= 1000
temp_preco_leblon = temp_leblon[preco_leblon]

condominios = temp_preco_leblon['condominio'].values.reshape(-1,1)
precos = temp_preco_leblon['preco'].values.flatten()

rl.fit(condominios, precos)

conds = [1000]
print('Condominios:', conds)

prec = rl.predict(np.array(conds).reshape(-1,1))
print('Precos:', prec)

plt.scatter(condominios, precos)
plt.scatter(conds, prec, color='red')
plt.plot([0,conds[0]],[0, int(prec)],color='red')