# -*- coding: utf-8 -*-
"""Guilherme de Paula Cardoso - Pandas_exercicio_enem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lfSxYoINMYoDfW4kloEedvlwYTBYEcvM

# Exercícios Pandas
"""

#Importação da biblioteca Pandas
import pandas as pd

"""# Base dados

## Fonte
Enem 1998  
[Microdados do Exame Nacional do Ensino Médio - Enem](http://www.dados.gov.br/dataset/microdados-do-exame-nacional-do-ensino-medio-enem)  

## Documentação da base
Para entender a base, acesse a descrição dos campos, disponível neste [link](https://docs.google.com/spreadsheets/d/1tKI5o9wBzBh_SaRccHJKwEzqIekqhyze/edit#gid=1105751035).

## Carregamento da base
Para carregar a base em um DataFrame Pandas, execute:
Para acessar o arquivo com a base é necessário solicitar acesso ao Google Drive. No caso desta aula, a base de dados está compartilhada entre todos os alunos incluídos na turma do Google Classroom.

### Google Colaboratory
Para execuções utilizando o ambiente do Google Colab, execute o código abaixo. A primeira vez que for executado, será solicitado um código de acesso. Para obter esse código, basta clicar no link gerado e seguir as instruções.
```python
#Solicita acesso ao Google Drive
from google.colab import drive
drive.mount('/drive')

#Carrega a base de dados direto do Google Drive (Executando no Google Colab)
enem98 = pd.read_csv('/drive/Shared drives/BasesPublicas/Bases/ENEM/1998/MICRODADOS_ENEM_1998.csv', sep=';', encoding='latin1' )
```
### Jupyter
Para execuções no Jupyter:
```python
#Colocar a base no mesmo diretório em que está executando o arquivo jupyter
#enem98 = pd.read_csv('MICRODADOS_ENEM_1998.csv', sep=';', encoding='latin1' )

``` 

"""

# Solicita acesso ao Google Drive
from google.colab import drive
drive.mount('/drive')

# Carrega a base de dados direto do Google Drive (Executando no Google Colab)
enem98 = pd.read_csv('/drive/Shared drives/BasesPublicas/Bases/ENEM/1998/MICRODADOS_ENEM_1998.csv', sep=';', encoding='latin1' )

"""# Responda
Sobre a base de dados referente ao ENEM do ano de 1998, responda as questões abaixo utilizando a biblioteca Pandas.

Sobre a base:
1. Quantas linhas existem na base?
1. Quantas colunas existem?
"""

enem98.shape

"""Obtenha cada informação solicitada a seguir:
- Quantos alunos foram matriculados?
"""

enem98['NU_INSCRICAO'].count()

"""- Quantos alunos matricularam-se no ENEM por estado?"""

enem98['SG_UF_RESIDENCIA'].value_counts()

"""- Quantos estudantes matriculados não realizaram a prova?"""

enem98['TP_PRESENCA'].value_counts()[0]

"""- Dos estudantes matriculados, quantos não realizaram a prova, por estado?"""

faltantes = enem98.iloc[enem98.index[enem98['TP_PRESENCA'] == 0]]
faltantes['SG_UF_RESIDENCIA'].value_counts()

"""- Qual é idade do(a) estudante mais velho(a)?"""

enem98['NU_IDADE'].max()

"""- Quantos estudantes empatam com a idade mais velha?"""

enem98['NU_IDADE'].value_counts()[enem98['NU_IDADE'].max()]

"""- Os estudantes com a idade mais mais velha são de quais estados?"""

velhos = enem98.iloc[enem98.index[enem98['NU_IDADE'] == enem98['NU_IDADE'].max()]]
velhos['SG_UF_RESIDENCIA'].value_counts()

"""- Qual é a idade do(a) estudante mais novo(a) do Paraná?"""

novo_pr = enem98.iloc[enem98.index[enem98['SG_UF_RESIDENCIA'] == "PR"]]
novo_pr['NU_IDADE'].min()

"""- Quantos estudantes possuem a mesma idade do estudante mais novo no Paraná?"""

enem98['NU_IDADE'].value_counts()[novo_pr['NU_IDADE'].min()]

"""- De quais cidades são os estudantes com a menor idade?"""

novos_cidade = enem98.iloc[enem98.index[enem98['NU_IDADE'] == novo_pr['NU_IDADE'].min()]]
novos_cidade['NO_MUNICIPIO_RESIDENCIA'].value_counts()

"""- No Paraná, qual a porcentagem de estudantes por sexo?"""

nmas = enem98['TP_SEXO'].value_counts()['M']
nfem = enem98['TP_SEXO'].value_counts()['F']
total = nfem+nmas
pmas = nmas*100/total
pfem = nfem*100/total
print("Porcentagem masculina", pmas)
print("Porcentagem feminina", pfem)